/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: Ibrahim BEMO
 *
 * Created on November 10, 2023, 5:37 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE 1U
#define INTERRUPT_ENABLE  1
#define INTERRUPT_DISABLE 1

//#define INTERRUPT_PRIORITY_LEVELS_ENABLE          INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE      INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_OnChange_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_ENABLE                        INTERRUPT_ENABLE
#define CCP1_INTERRUPT_ENABLE                       INTERRUPT_ENABLE
#define TIMER0_INTERRUPT_ENABLE                     INTERRUPT_ENABLE
#define TIMER1_INTERRUPT_ENABLE                     INTERRUPT_ENABLE
#define TIMER2_INTERRUPT_ENABLE                     INTERRUPT_ENABLE
#define TIMER3_INTERRUPT_ENABLE                     INTERRUPT_ENABLE

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

